# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

ENV['RCT_NEW_ARCH_ENABLED'] = '0'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'QvTransportersAppUi' do
  config = use_native_modules!

  pod 'GoogleUtilities', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.build_configurations.each do |configuration|
      configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      configuration.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'
    end

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |configuration|
        configuration.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
        configuration.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'

        if target.name == 'fmt'
          definitions = configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
          definitions = [definitions] unless definitions.is_a?(Array)
          definitions << 'FMT_USE_CONSTEVAL=0' unless definitions.include?('FMT_USE_CONSTEVAL=0')
          configuration.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = definitions
        end
      end

      next unless target.respond_to?(:source_build_phase)

      target.source_build_phase.files.each do |build_file|
        next unless build_file.settings && build_file.settings['COMPILER_FLAGS']

        build_file.settings['COMPILER_FLAGS'] = build_file.settings['COMPILER_FLAGS'].gsub(/\s*-Werror\b/, '')
      end
    end
  end
end
